django_movie/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('contact/', include('contact.urls')),
    path('', include('movies.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.MoviesView.as_view(), name="movie_list_url"),
    path("filter/", views.FilterMoviesView.as_view(), name="filter_url"),
    path("search/", views.Search.as_view(), name='search_url'),
    path("add-rating/", views.AddStarRating.as_view(), name="add_rating_url"),
    path("<slug:slug>/", views.MovieDetailView.as_view(), name='movie_detail_url'),
    path("review/<int:pk>/", views.AddReview.as_view(), name="add_review_url"),
    path("actor/<str:slug>/", views.ActorView.as_view(), name="actor_detail_url"),
]

movies/models.py
from datetime import date
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField("Категория", max_length=150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Actor(models.Model):
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="actors/")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Актеры и режиссеры"
        verbose_name_plural = "Актеры и режиссеры"

    def get_absolute_url(self):
        return reverse("actor_detail_url", kwargs={"slug": self.name})


class Genre(models.Model):
    name = models.CharField("Имя", max_length=100)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Movie(models.Model):
    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Дата выхода", default=2020)
    country = models.CharField("Страна", max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name="режиссер", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="актеры", related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="жанры")
    world_premiere = models.DateField("Премьера в мире", default=date.today)
    budget = models.PositiveIntegerField("Бюджет", default=0, help_text="указывать сумму в долларах")
    fees_in_usa = models.PositiveIntegerField(
        "Сборы в США", default=0, help_text="указывать сумму в долларах"
    )
    fees_in_world = models.PositiveIntegerField(
        "Сборы в мире", default=0, help_text="указывать сумму в долларах"
    )
    category = models.ForeignKey(
        Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True
    )
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie_detail_url', kwargs={'slug': self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"


class MovieShots(models.Model):
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField('Описание')
    image = models.ImageField("Изображение", upload_to='movies_shots/')
    movie = models.ForeignKey(Movie, verbose_name='Фильм', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"


class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.PositiveSmallIntegerField('Значение', default=0)

    def __str__(self):
        return f"{self.value}"

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField('IP адрес', max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="звезда")
    movie = models.ForeignKey(Movie, on_delete=models.CharField, verbose_name='Фильм')

    def __str__(self):
        return f'{self.star} - {self.movie}'

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = 'Рейтинги'


class Reviews(models.Model):
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField('Сообщение', max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name='Родитель', on_delete=models.SET_NULL, blank=True, null=True
    )
    movie = models.ForeignKey(Movie, verbose_name='Фильм', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} - {self.movie}'

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

movies/forms.py
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField

from .models import Reviews, Rating, RatingStar


class ReviewForm(forms.ModelForm):
    """Форма отзывов"""
    captcha = ReCaptchaField()

    class Meta:
        model = Reviews
        fields = ("name", "email", "text", "captcha")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "text": forms.Textarea(attrs={"class": "form-control",
                                          "id": "contactcomment"})
        }


class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)

movies/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView
from django.views import View

from .models import Movie, Actor, Genre, Rating

from .forms import ReviewForm, RatingForm


class GenreYear:
    """Жанры и года выхода фильмов"""
    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Movie.objects.filter(draft=False).values_list("year", flat=True).distinct()


class MoviesView(GenreYear, ListView):
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    paginate_by = 4


class MovieDetailView(GenreYear, DetailView):
    """Полное описание фильма"""
    model = Movie
    slug_field = "url"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["star_form"] = RatingForm()
        context["form"] = ReviewForm()
        return context


class AddReview(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())


class ActorView(GenreYear, DetailView):
    model = Actor
    template_name = 'movies/actor.html'
    slug_field = 'name'


class FilterMoviesView(GenreYear, ListView):
    """Фильтр фильмов"""
    paginate_by = 4

    def get_queryset(self):
        if self.request.GET.getlist("genre") and not self.request.GET.getlist("year"):
            queryset = Movie.objects.filter(genres__in=self.request.GET.getlist("genre")).distinct()
            return queryset

        elif self.request.GET.getlist("year") and not self.request.GET.getlist("genre"):
            queryset = Movie.objects.filter(year__in=self.request.GET.getlist("year")).distinct()
            return queryset

        elif self.request.GET.getlist("year") and self.request.GET.getlist("genre"):
            queryset = Movie.objects.filter(
                                            year__in=self.request.GET.getlist("year"),
                                            genres__in=self.request.GET.getlist("genre")
                                            ).distinct()
            return queryset

        queryset = Movie.objects.all()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["year"] = ''.join([f"year={x}&" for x in self.request.GET.getlist("year")])
        context["genre"] = ''.join([f"genre={x}&" for x in self.request.GET.getlist("genre")])
        return context


class AddStarRating(View):
    """Добавление рейтинга к фильму"""
    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
            print(x_forwarded_for)
        else:
            ip = request.META.get('REMOTE_ADDR')
            print(request.META.get('REMOTE_ADDR'))
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class Search(GenreYear, ListView):
    """Поиск фильма"""
    paginate_by = 4

    def get_queryset(self):
        return Movie.objects.filter(title__icontains=self.request.GET.get('q'))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'
        return context

movies/templates/movies/actor.html
{% extends 'base.html' %}
{% load static %}


{% block styles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% endblock %}

{% block title %}
	DjangoMovie - {{actor.title}}
{% endblock %}


{% block content %}

<div class="container mt-2">
	<div class="row">
		<div class="col-3">
			<img src="{{ actor.image.url }}" class="mt-2" style="height: 22rem; width: 18rem">
		</div>

		<div class="col-6" style="padding: 0 5em;">
			<h1><span>{{ actor.name }}</span></h1>

			<p><span>Возраст: {{ actor.age }}</span></p>

			<p><span>Режиссёр:</span>
				{% for movie in actor.film_director.all %}
					{{ movie.title }}
				{% endfor %}
			</p>

			<p><span>Актёр:</span>
				{% for movie in actor.film_actor.all %}
					{{ movie.title }}
				{% endfor %}
			</p>


		</div>
	</div>
		<div class="mt-5 mb-3" style="display: flex; justify-content: space-around;">
			<h3>О {{ actor.name }}</h3>
		</div>
		<p>{{ actor.description }}</p>

</div>
</div>

{% endblock %}

movies/templates/movies/movie_detail.html
{% extends 'base.html' %}
{% load static %}


{% block styles %}

{% endblock %}

{% block title %}
DjangoMovie - {{movie.title}}
{% endblock %}


{% block content %}
<div class="container mt-2">
	<div class="row">
		<div class="col-3">
			<img src="{{ movie.poster.url }}" class="mt-2" style="width: 100%;">
		</div>

		<div class="col-6" style="padding-left: 5em;">
			<h1><span>{{ movie.title }}</span></h1>

			<h5><span>{{ movie.tagline }}</span></h5>

			<p><span>Дата выхода:</span> {{ movie.year }}</p>
			<p><span>Страны: </span>{{ movie.country }}</p>
			<p><span>Режиссёр: </span>

				{% for director in movie.directors.all %}
				<a href="{{ director.get_absolute_url }}">
					{{ director.name }}
				</a>
				{% endfor %}


			</p>
			<p><span>Актёры: </span>

				{% for actor in movie.actors.all %}
				<a href="{{ actor.get_absolute_url }}">
					{{ actor.name }}
				</a>
				{% endfor %}

			</p>
			<p><span>Жанры: </span>

				{% for genre in movie.genres.all %}
				{{ genre.name }}
				{% endfor %}

			</p>
			<p><span>Премьера в мире: </span>{{ movie.world_premiere }}</p>
			<p><span>Бюджет: </span>${{ movie.budget }}</p>
			<p><span>Сборы в США: </span>${{ movie.fees_in_usa }}</p>
			<p><span>Сборы в мире: </span>${{ movie.fees_in_world }}</p>

			<form action="{% url 'add_rating_url' %}" method="post" name="rating">
				<b>Рейтинг:</b>
				{% csrf_token %}
				<input type="hidden" value="{{ movie.id }}" name="movie">
				<span class="rating">
					{% for k, v in star_form.fields.star.choices %}
						<input type="radio" id="rating{{ v }}" name="star" value="{{ k }}">
						<label for="rating{{ v }}">{{ k }}</label>
					{% endfor %}
				</span>
			</form>
		</div>

		<div class="col-12 mt-5">
			<h5 class="mb-3" style="text-align: center;">Кадры из фильма</h5>
			{% for image in movie.movieshots_set.all %}
			<img src="{{ image.image.url }}" class="img-movie-shots" alt="{{ image.description }}">
			{% endfor %}
		</div>

		<div class="col-12 mt-5">
			<p style="text-indent: 25px;">{{ movie.description|safe }}</p>
		</div>

		<div class="col-6 offset-md-3 mt-5">
			<h3>Оставить отзыв:</h3>

			<form action="{% url 'add_review_url' movie.id %}" method="post" id='formReview'>
				{% csrf_token %}
				<input type="hidden" name="parent" id="contactparent" value="">
				<div class="form-group">
					<label for="contactcomment">Ваш комментарий *</label>
					{{ form.text }}
				</div>
				<div class="form-group">
					<label for="exampleInputEmail1">Email</label>
					{{ form.email }}
				</div>
				<div class="form-group">
					<label for="exampleInput">Имя</label>
					{{ form.name }}
				</div>
				{{ form.captcha }}
				<button type="submit" class="btn btn-primary" style="position: relative; left: 50%; transform: translate(-50%, 0);">Отправить</button>
			</form>

			<div class="mt-5">
				<div>
					<span style="font-size: 10px;">{{ movie.reviews_set.count }}</span>
					<h4 class="mb-4">Отзывы:</h4>
				</div>

				{% for review in movie.get_review %}
				<div class="mb-3">
					<h5>
						{{ review.name }}
					</h5>
					<p style="margin: 3px 0;">
						{{ review.text }}
					</p>
					<a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>
				</div>

					{% for rew in review.reviews_set.all %}
					<div class="ml-4 mb-3">
						<h5>
							{{ rew.name }}
						</h5>
						<p style="margin: 3px 0;">
							{{ rew.text }}
						</p>
					</div>
					{% endfor %}
				{% endfor %}
			</div>
		</div>
	</div>
</div>

<script>
	function addReview(name, id) {
		document.getElementById("contactparent").value = id;
		document.getElementById("contactcomment").innerText = `${name},`
	}
</script>

{% endblock %}

movies/templates/movies/movie_list.html
{% extends 'base.html' %}
{% load movie_tag %}

{% block title %}
DjangoMovie
{% endblock %}

{% block content %}
<main>
	<div class="row" style="padding: 0 0; margin: 0 0;">
		<div class="col-3">
			<form class="form-inline my-2 my-lg-0" action="{% url 'search_url' %}" method="get">
				<input class="form-control mr-sm-2 mt-2" type="search" name='q' placeholder="Введите название..." aria-label="Search" style="width: 65%">
				<div class="mt-2">
					<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
				</div>
			</form>	

			<form action="{% url 'filter_url' %}" method="get" name="filter">
				<div class="mt-5">
					<h5>Жанры</h5>
					{% for genre in view.get_genres %}
					<li class="mt-3" style="list-style-type: none;">
						<input type="checkbox" name="genre" value="{{ genre.id }}">
						<span class="ml-2">{{ genre.name|title }}</span>
					</li>
					{% endfor %}
				</div>

				<div class="mt-5">
					<h5>Год</h5>
					{% for year in view.get_years %}
					<li class="mt-3" style="list-style-type: none">
						<input type="checkbox" name="year" value="{{ year }}">
						<span class="ml-2">{{ year }}</span>
					</li>
					{% endfor %}
				</div>
				<button class="btn btn-outline-success mt-3" type="submit">Найти</button>
			</form>

			{% get_last_movies count=5 %}
		</div>



		<div class="col-9 mt-2">
			<div class="row">
				{% for movie in movie_list %}
				<div class="card mr-5 mb-5" style="width: 265px; height: 580px;">
					<img src="{{ movie.poster.url }}" class="card-img-top" alt="..." style="height: 380px;">
					<div class="card-body">
						<a href="{{ movie.get_absolute_url }}">
							<h5 class="card-title" style="text-align: center;">{{ movie.title }}</h5>
						</a>
						<p class="card-text">{{ movie.tagline }} </p>
					</div>
					<ul class="list-group list-group-flush">
						<li class="list-group-item">Рейтинг: </li>
					</ul>
				</div>
				{% endfor %}
			</div>
			{% include 'include/pagination.html' %}
			</div>
		</div>
	</div>
</main>

{% endblock %}